server.port=8090
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
bank.simulator.url=http://localhost:8080

resilience4j.circuitbreaker.instances.bank.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.bank.sliding-window-size=10
resilience4j.circuitbreaker.instances.bank.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.bank.wait-duration-in-open-state=10s

resilience4j.ratelimiter.instances.bank.limit-for-period=10
resilience4j.ratelimiter.instances.bank.limit-refresh-period=1s
resilience4j.ratelimiter.instances.bank.timeout-duration=0
